repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        files: ^apps/backend/python/.*\.py$
        args: [--line-length=100]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.9
    hooks:
      - id: ruff
        files: ^apps/backend/python/.*\.py$
        args: [--fix]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.7.1
    hooks:
      - id: mypy
        files: ^apps/backend/python/src/.*\.py$
        additional_dependencies:
          - pydantic
          - fastapi

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: ^apps/frontend/web/src/.*\.(ts|tsx)$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - "@typescript-eslint/eslint-plugin@6.15.0"
          - "@typescript-eslint/parser@6.15.0"
          - eslint-plugin-react-hooks@4.6.0
          - eslint-plugin-react-refresh@0.4.5

  - repo: local
    hooks:
      - id: go-fmt
        name: Go Format
        entry: bash -c 'cd apps/backend/go && gofmt -w -s .'
        language: system
        files: ^apps/backend/go/.*\.go$
        pass_filenames: false

      - id: go-vet
        name: Go Vet
        entry: bash -c 'cd apps/backend/go && go vet ./...'
        language: system
        files: ^apps/backend/go/.*\.go$
        pass_filenames: false
