version: '3.9'

services:
  # Backend Services
  auditlog-service:
    build:
      context: ./apps/backend/go/auditlog-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - AUDITLOG_SERVICE_PORT=8080
    restart: unless-stopped

  audit-service-python:
    build:
      context: ./apps/backend/python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
    restart: unless-stopped

  # Frontend
  web-frontend:
    build:
      context: ./apps/frontend/web
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    restart: unless-stopped

  # Observability Stack
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.10.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    depends_on:
      - elasticsearch

  prometheus:
    image: prom/prometheus:v2.48.0
    volumes:
      - ./config/monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/monitoring/security_rules.yml:/etc/prometheus/security_rules.yml
      - ./config/monitoring/compliance_rules.yml:/etc/prometheus/compliance_rules.yml
    ports:
      - "9090:9090"

  alertmanager:
    image: prom/alertmanager:v0.26.0
    volumes:
      - ./config/monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
    ports:
      - "9093:9093"
    depends_on:
      - prometheus

  grafana:
    image: grafana/grafana:10.2.0
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-data:/var/lib/grafana

volumes:
  elasticsearch-data:
  grafana-data:
