syncSecret:
  enabled: true

enableSecretRotation: true
rotationPollInterval: 120s

linux:
  enabled: true
  image:
    repository: registry.k8s.io/csi-secrets-store/driver
    pullPolicy: IfNotPresent
  
  driver:
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 50m
        memory: 128Mi

  registrarImage:
    repository: registry.k8s.io/sig-storage/csi-node-driver-registrar
    pullPolicy: IfNotPresent

  livenessProbeImage:
    repository: registry.k8s.io/sig-storage/livenessprobe
    pullPolicy: IfNotPresent

rbac:
  install: true

metrics:
  enabled: true
