apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-realtime
  labels:
    app: ws-realtime
    component: websocket-gateway
    tier: realtime
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ws-realtime
      component: websocket-gateway
  template:
    metadata:
      labels:
        app: ws-realtime
        component: websocket-gateway
        tier: realtime
    spec:
      containers:
        - name: ws-realtime
          image: ghcr.io/example/ws-realtime:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: ws-realtime-config
            - secretRef:
                name: ws-realtime-secret
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
            timeoutSeconds: 3
            failureThreshold: 5
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
